datamodule:
    target: data_modules.vg.VGDataModule
    params: 
        image_size: 256
        base_path: data/VisualGenome
        pos_enc_dim: 8
        max_objects: 30
        train_h5: train.h5
        val_h5: val.h5

trainer:
    target: trainers.t_sgtransformer.TrainerSGTransformer
    params:
        base_lr: 0.00001 # 1e-5
        scheduler: onecycle
        lr_scheduler: 
            max_lr: 0.0003 # 3e-4

        sgtransformer_config: config/sgtransformer.yaml
        device: cuda
        epochs: 300
        box_beta: 10