target: modules.vqvae.vqgan.VQModel
params:
    ckpt_path: weights/vqmodel/K8192/coco.pt
    embed_dim: 256
    emb_size: 8192
    ddconfig:
        double_z: false
        z_channels: 256
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult:
        - 1
        - 1
        - 2
        - 2
        - 4
        num_res_blocks: 2
        attn_resolutions:
        - 16
        dropout: 0.0